version: '2'
services:
  web:
    build: .
    command: rackup --port 4567 --host 0.0.0.0
    volumes:
      - .:/usr/src/app
    volumes_from:
      - bundle
    ports:
      - "4567:4567"
  bundle:
    # You may need to run `docker-compose build web` before this works.
    image: alpine
    command: echo "I'm a little data volume, short and stout"
    volumes:
      - /bundle
